version: '3.7'
services:
  alba:
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: alba
    ports:
      - '8001:8001'
    container_name: 'alba'
    volumes:
      - '.:/var/www/html'
    networks:
      - alba

  mysql:
    image: 'mysql:8.0'
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'alba'
      MYSQL_USER: 'alba'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'alba:/var/lib/mysql'
    networks:
      - alba

networks:
  alba:
    driver: bridge
volumes:
  alba:
    driver: local